#include <oqs/oqs.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#define ITERATIONS 20
static double ns(struct timespec a, struct timespec b){return (double)(b.tv_sec-a.tv_sec)*1e9+(double)(b.tv_nsec-a.tv_nsec);}
static void emit(const char *alg,const char *param,const char *op,double lat,size_t pk,size_t sk,size_t ct,size_t sig){printf("{\"schema_version\":1,\"run_id\":\"liboqs-%s-%s\",\"implementation\":{\"id\":\"liboqs\",\"version\":\"0.16.0\",\"commit\":null},\"algorithm\":{\"id\":\"%s\",\"parameter_set\":\"%s\"},\"operation\":\"%s\",\"environment\":{\"target\":\"native\",\"os\":\"unknown\",\"cpu\":\"unknown\",\"cpu_features\":[],\"compiler\":\"cc\",\"compiler_version\":\"unknown\",\"optimization\":\"unknown\",\"harness_version\":\"arena-v1\"},\"measurement\":{\"iterations\":%d,\"warmups\":0,\"latency_ns\":%.3f,\"throughput_ops_s\":%.6f,\"memory_bytes\":null,\"measurement_method\":\"clock_gettime(CLOCK_MONOTONIC) mean wall-clock latency\"},\"sizes\":{\"public_key_bytes\":%zu,\"secret_key_bytes\":%zu,\"ciphertext_bytes\":%zu,\"signature_bytes\":%zu}}\n",alg,param,alg,param,op,ITERATIONS,lat,1e9/lat,pk,sk,ct,sig);}
static int kem(const char *name,const char *param){OQS_KEM *k=OQS_KEM_new(name);if(!k)return 1;uint8_t *pk=malloc(k->length_public_key),*sk=malloc(k->length_secret_key),*ct=malloc(k->length_ciphertext),*ss=malloc(k->length_shared_secret);if(!pk||!sk||!ct||!ss)return 2;struct timespec a,b;clock_gettime(CLOCK_MONOTONIC,&a);for(int i=0;i<ITERATIONS;i++)if(OQS_KEM_keypair(k,pk,sk)!=OQS_SUCCESS)return 3;clock_gettime(CLOCK_MONOTONIC,&b);emit("ml-kem",param,"keygen",ns(a,b)/ITERATIONS,k->length_public_key,k->length_secret_key,k->length_ciphertext,0);if(OQS_KEM_keypair(k,pk,sk)!=OQS_SUCCESS)return 4;clock_gettime(CLOCK_MONOTONIC,&a);for(int i=0;i<ITERATIONS;i++)if(OQS_KEM_encaps(k,ct,ss,pk)!=OQS_SUCCESS)return 5;clock_gettime(CLOCK_MONOTONIC,&b);emit("ml-kem",param,"encaps",ns(a,b)/ITERATIONS,k->length_public_key,k->length_secret_key,k->length_ciphertext,0);if(OQS_KEM_encaps(k,ct,ss,pk)!=OQS_SUCCESS)return 6;clock_gettime(CLOCK_MONOTONIC,&a);for(int i=0;i<ITERATIONS;i++)if(OQS_KEM_decaps(k,ss,ct,sk)!=OQS_SUCCESS)return 7;clock_gettime(CLOCK_MONOTONIC,&b);emit("ml-kem",param,"decaps",ns(a,b)/ITERATIONS,k->length_public_key,k->length_secret_key,k->length_ciphertext,0);free(pk);free(sk);free(ct);free(ss);OQS_KEM_free(k);return 0;}
static int sig(const char *name,const char *param){OQS_SIG *s=OQS_SIG_new(name);if(!s)return 1;uint8_t *pk=malloc(s->length_public_key),*sk=malloc(s->length_secret_key),*buf=malloc(s->length_signature);size_t sl=0;const uint8_t msg[]="nexusq-pqc-arena-v1";if(!pk||!sk||!buf)return 2;struct timespec a,b;clock_gettime(CLOCK_MONOTONIC,&a);for(int i=0;i<ITERATIONS;i++)if(OQS_SIG_keypair(s,pk,sk)!=OQS_SUCCESS)return 3;clock_gettime(CLOCK_MONOTONIC,&b);emit("ml-dsa",param,"keygen",ns(a,b)/ITERATIONS,s->length_public_key,s->length_secret_key,0,s->length_signature);if(OQS_SIG_keypair(s,pk,sk)!=OQS_SUCCESS)return 4;clock_gettime(CLOCK_MONOTONIC,&a);for(int i=0;i<ITERATIONS;i++)if(OQS_SIG_sign(s,buf,&sl,msg,sizeof(msg)-1,sk)!=OQS_SUCCESS)return 5;clock_gettime(CLOCK_MONOTONIC,&b);emit("ml-dsa",param,"sign",ns(a,b)/ITERATIONS,s->length_public_key,s->length_secret_key,0,sl);if(OQS_SIG_sign(s,buf,&sl,msg,sizeof(msg)-1,sk)!=OQS_SUCCESS)return 6;clock_gettime(CLOCK_MONOTONIC,&a);for(int i=0;i<ITERATIONS;i++)if(OQS_SIG_verify(s,msg,sizeof(msg)-1,buf,sl,pk)!=OQS_SUCCESS)return 7;clock_gettime(CLOCK_MONOTONIC,&b);emit("ml-dsa",param,"verify",ns(a,b)/ITERATIONS,s->length_public_key,s->length_secret_key,0,sl);free(pk);free(sk);free(buf);OQS_SIG_free(s);return 0;}
int main(void){if(OQS_init()!=OQS_SUCCESS)return 10;int rc=kem("ML-KEM-768","768");rc|=kem("ML-KEM-1024","1024");rc|=sig("ML-DSA-65","65");OQS_destroy();return rc;}
