#define _POSIX_C_SOURCE 200809L
#include <openssl/evp.h>
#include <openssl/base.h>
#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <time.h>
#include <sys/utsname.h>

#define DEFAULT_ITERATIONS 20
#define DEFAULT_WARMUPS 3
#define MESSAGE "nexusq-pqc-arena-v1"

static double elapsed_ns(struct timespec a, struct timespec b){return (double)(b.tv_sec-a.tv_sec)*1e9+(double)(b.tv_nsec-a.tv_nsec);}
static int configured_count(const char *name, int fallback, int minimum) {
    const char *value = getenv(name);
    if (value == NULL || *value == '\0') return fallback;
    char *end = NULL;
    long parsed = strtol(value, &end, 10);
    if (end == value || *end != '\0' || parsed < minimum || parsed > 1000000L) {
        fprintf(stderr, "%s must be an integer in [%d, 1000000]; got '%s'\n", name, minimum, value);
        exit(64);
    }
    return (int)parsed;
}
static int iterations(void) { return configured_count("AWSLC_ITERATIONS", DEFAULT_ITERATIONS, 1); }
static int warmups(void) { return configured_count("AWSLC_WARMUPS", DEFAULT_WARMUPS, 0); }
static const char *env_or(const char*n,const char*f){const char*v=getenv(n);return v&&*v?v:f;}
static void meta(char*t,size_t tl,char*o,size_t ol,char*c,size_t cl){struct utsname u;if(getenv("ARENA_TARGET")&&getenv("ARENA_OS")&&getenv("ARENA_CPU")){snprintf(t,tl,"%s",getenv("ARENA_TARGET"));snprintf(o,ol,"%s",getenv("ARENA_OS"));snprintf(c,cl,"%s",getenv("ARENA_CPU"));return;}if(uname(&u)==0){snprintf(t,tl,"%s-%s",u.machine,u.sysname);snprintf(o,ol,"%s",u.sysname);snprintf(c,cl,"%s",u.machine);return;}snprintf(t,tl,"unknown");snprintf(o,ol,"unknown");snprintf(c,cl,"unknown");}
static void emit(const char*a,const char*p,const char*op,double lat,size_t pk,size_t sk,size_t ct,size_t sig,int hasct,int hassig){char t[256],o[128],c[256],cj[32],sj[32];struct timespec ts;meta(t,sizeof(t),o,sizeof(o),c,sizeof(c));clock_gettime(CLOCK_REALTIME,&ts);snprintf(cj,sizeof(cj),hasct?"%zu":"null",ct);snprintf(sj,sizeof(sj),hassig?"%zu":"null",sig);unsigned long long stamp=(unsigned long long)ts.tv_sec*1000000000ULL+(unsigned long long)ts.tv_nsec;printf("{\"schema_version\":1,\"run_id\":\"aws-lc-%s-%s-%s\",\"implementation\":{\"id\":\"aws-lc\",\"version\":\"%s\",\"commit\":\"ec05f25\"},\"algorithm\":{\"id\":\"%s\",\"parameter_set\":\"%s\"},\"operation\":\"%s\",\"environment\":{\"target\":\"%s\",\"os\":\"%s\",\"cpu\":\"%s\",\"cpu_features\":[],\"compiler\":\"cc\",\"compiler_version\":\"%s\",\"optimization\":\"%s\",\"harness_version\":\"arena-v1\"},\"measurement\":{\"iterations\":%d,\"warmups\":%d,\"measurement_timestamp_unix_ns\":%llu,\"latency_ns\":%.3f,\"throughput_ops_s\":%.6f,\"memory_bytes\":null,\"measurement_method\":\"clock_gettime(CLOCK_MONOTONIC) mean wall-clock latency\"},\"sizes\":{\"public_key_bytes\":%zu,\"secret_key_bytes\":%zu,\"ciphertext_bytes\":%s,\"signature_bytes\":%s}}\n",a,p,op,env_or("AWSLC_VERSION", "runtime"),a,p,op,t,o,c,__VERSION__,env_or("ARENA_OPT","release"),iterations(),warmups(),stamp,lat,1e9/lat,pk,sk,cj,sj);}
static int kem(void){EVP_PKEY *key=NULL;EVP_PKEY_CTX*ctx=NULL;unsigned char*ct=NULL,*ss=NULL;size_t ctl=0,ssl=0;struct timespec a,b;for(int w=0;w<warmups();w++){ctx=EVP_PKEY_CTX_new_id(EVP_PKEY_KEM,NULL);if(!ctx||!EVP_PKEY_keygen_init(ctx)||!EVP_PKEY_CTX_kem_set_params(ctx,NID_MLKEM768)||!EVP_PKEY_keygen(ctx,&key))return 1;EVP_PKEY_CTX_free(ctx);ctx=NULL;EVP_PKEY_free(key);key=NULL;}clock_gettime(CLOCK_MONOTONIC,&a);for(int i=0;i<iterations();i++){ctx=EVP_PKEY_CTX_new_id(EVP_PKEY_KEM,NULL);if(!ctx||!EVP_PKEY_keygen_init(ctx)||!EVP_PKEY_CTX_kem_set_params(ctx,NID_MLKEM768)||!EVP_PKEY_keygen(ctx,&key))return 2;EVP_PKEY_CTX_free(ctx);ctx=NULL;EVP_PKEY_free(key);key=NULL;}clock_gettime(CLOCK_MONOTONIC,&b);emit("ml-kem","768","keygen",elapsed_ns(a,b)/iterations(),1184,2400,1088,0,1,0);
ctx=EVP_PKEY_CTX_new_id(EVP_PKEY_KEM,NULL);if(!ctx||!EVP_PKEY_keygen_init(ctx)||!EVP_PKEY_CTX_kem_set_params(ctx,NID_MLKEM768)||!EVP_PKEY_keygen(ctx,&key))return 3;EVP_PKEY_CTX_free(ctx);ctx=NULL;ctx=EVP_PKEY_CTX_new(key,NULL);if(!ctx||!EVP_PKEY_encapsulate(ctx,NULL,&ctl,NULL,&ssl))return 4;ct=OPENSSL_malloc(ctl);ss=OPENSSL_malloc(ssl);if(!ct||!ss)return 5;EVP_PKEY_CTX_free(ctx);ctx=NULL;for(int w=0;w<warmups();w++){ctx=EVP_PKEY_CTX_new(key,NULL);if(!ctx||!EVP_PKEY_encapsulate(ctx,ct,&ctl,ss,&ssl))return 6;EVP_PKEY_CTX_free(ctx);ctx=NULL;}clock_gettime(CLOCK_MONOTONIC,&a);for(int i=0;i<iterations();i++){ctx=EVP_PKEY_CTX_new(key,NULL);if(!ctx||!EVP_PKEY_encapsulate(ctx,ct,&ctl,ss,&ssl))return 7;EVP_PKEY_CTX_free(ctx);ctx=NULL;}clock_gettime(CLOCK_MONOTONIC,&b);emit("ml-kem","768","encaps",elapsed_ns(a,b)/iterations(),1184,2400,ctl,0,1,0);for(int w=0;w<warmups();w++){ctx=EVP_PKEY_CTX_new(key,NULL);if(!ctx||!EVP_PKEY_decapsulate(ctx,ss,&ssl,ct,ctl))return 8;EVP_PKEY_CTX_free(ctx);ctx=NULL;}clock_gettime(CLOCK_MONOTONIC,&a);for(int i=0;i<iterations();i++){ctx=EVP_PKEY_CTX_new(key,NULL);if(!ctx||!EVP_PKEY_decapsulate(ctx,ss,&ssl,ct,ctl))return 9;EVP_PKEY_CTX_free(ctx);ctx=NULL;}clock_gettime(CLOCK_MONOTONIC,&b);emit("ml-kem","768","decaps",elapsed_ns(a,b)/iterations(),1184,2400,ctl,0,1,0);OPENSSL_free(ct);OPENSSL_free(ss);EVP_PKEY_free(key);return 0;}
static int dsa(void){EVP_PKEY*key=NULL;EVP_PKEY_CTX*kctx=NULL;EVP_MD_CTX*md=NULL;unsigned char sig[4096];size_t sl=sizeof(sig);const unsigned char msg[]=MESSAGE;struct timespec a,b;for(int w=0;w<warmups();w++){kctx=EVP_PKEY_CTX_new_id(EVP_PKEY_PQDSA,NULL);if(!kctx||!EVP_PKEY_keygen_init(kctx)||!EVP_PKEY_CTX_pqdsa_set_params(kctx,NID_MLDSA65)||!EVP_PKEY_keygen(kctx,&key))return 1;EVP_PKEY_CTX_free(kctx);kctx=NULL;EVP_PKEY_free(key);key=NULL;}clock_gettime(CLOCK_MONOTONIC,&a);for(int i=0;i<iterations();i++){kctx=EVP_PKEY_CTX_new_id(EVP_PKEY_PQDSA,NULL);if(!kctx||!EVP_PKEY_keygen_init(kctx)||!EVP_PKEY_CTX_pqdsa_set_params(kctx,NID_MLDSA65)||!EVP_PKEY_keygen(kctx,&key))return 2;EVP_PKEY_CTX_free(kctx);kctx=NULL;EVP_PKEY_free(key);key=NULL;}clock_gettime(CLOCK_MONOTONIC,&b);emit("ml-dsa","65","keygen",elapsed_ns(a,b)/iterations(),1952,4032,0,3309,0,1);kctx=EVP_PKEY_CTX_new_id(EVP_PKEY_PQDSA,NULL);if(!kctx||!EVP_PKEY_keygen_init(kctx)||!EVP_PKEY_CTX_pqdsa_set_params(kctx,NID_MLDSA65)||!EVP_PKEY_keygen(kctx,&key))return 3;EVP_PKEY_CTX_free(kctx);for(int w=0;w<warmups();w++){md=EVP_MD_CTX_new();if(!md||!EVP_DigestSignInit(md,NULL,NULL,NULL,key)||!EVP_DigestSign(md,sig,&sl,msg,sizeof(msg)-1))return 4;EVP_MD_CTX_free(md);sl=sizeof(sig);}clock_gettime(CLOCK_MONOTONIC,&a);for(int i=0;i<iterations();i++){md=EVP_MD_CTX_new();if(!md||!EVP_DigestSignInit(md,NULL,NULL,NULL,key)||!EVP_DigestSign(md,sig,&sl,msg,sizeof(msg)-1))return 5;EVP_MD_CTX_free(md);sl=sizeof(sig);}clock_gettime(CLOCK_MONOTONIC,&b);emit("ml-dsa","65","sign",elapsed_ns(a,b)/iterations(),1952,4032,0,3309,0,1);for(int w=0;w<warmups();w++){md=EVP_MD_CTX_new();if(!md||!EVP_DigestVerifyInit(md,NULL,NULL,NULL,key)||!EVP_DigestVerify(md,sig,3309,msg,sizeof(msg)-1))return 6;EVP_MD_CTX_free(md);}clock_gettime(CLOCK_MONOTONIC,&a);for(int i=0;i<iterations();i++){md=EVP_MD_CTX_new();if(!md||!EVP_DigestVerifyInit(md,NULL,NULL,NULL,key)||!EVP_DigestVerify(md,sig,3309,msg,sizeof(msg)-1))return 7;EVP_MD_CTX_free(md);}clock_gettime(CLOCK_MONOTONIC,&b);emit("ml-dsa","65","verify",elapsed_ns(a,b)/iterations(),1952,4032,0,3309,0,1);EVP_PKEY_free(key);return 0;}
int main(void){if(kem()!=0)return 1;if(dsa()!=0)return 2;return 0;}
