[package]
name = "nexusq-c"
description = "C bindings for NEXUS-Q"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "nexusq"
crate-type = ["cdylib", "staticlib"]

[dependencies]
nexusq-core = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
